apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aspnetapp
  namespace: aspnetapp-staging
  labels:
    app.kubernetes.io/name: aspnetapp
    app.kubernetes.io/part-of: dotnet-aspnetapp

spec:
  minAvailable: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: aspnetapp
      app.kubernetes.io/part-of: dotnet-aspnetapp
