apiVersion: v1
kind: ServiceAccount
metadata:
  name: aspnetapp
  namespace: aspnetapp-staging
  labels:
    app.kubernetes.io/name: aspnetapp
    app.kubernetes.io/part-of: dotnet-aspnetapp

automountServiceAccountToken: false

imagePullSecrets:
  - name: ecr-registry
